#!/bin/bash
cd ../src
if [ $# -gt 1 ]; then
	cd $2
fi
grep -r "dojo\.$1\." * | grep -v "\.svn" | grep -v -e 'dojo\.require\|dojo\.provide\|moduleLoaded' |\
sed -r 's/^.*(dojo\.'$1'\.[a-zA-Z0-9_\.]+).*$/\1/' | sed -r 's/\.(apply|call)$//' | sort | uniq -c | sort -g -r
