var dependencies = [ 
	"dojo.lang",
	"dojo.html.*",
	"dojo.html.display",
	"dojo.html.layout",
	"dojo.html.util",
	"dojo.lfx.*",
	"dojo.event.*",
	"dojo.logging.*",
	"dojo.io.*",
	"dojo.io.IframeIO",
	"dojo.date",
	"dojo.string.*",
	"dojo.regex",
	"dojo.rpc.*",
	"dojo.xml.*",
	// "dojo.flash.*",
	// "dojo.storage.*",
	"dojo.undo.*",
	"dojo.crypto.*",
	//"dojo.collections.*",
	"dojo.collections.ArrayList",
	"dojo.collections.Collections",
	"dojo.collections.Queue",
	"dojo.collections.Stack",
	"dojo.dnd.*",
	"dojo.widget.*",
	"dojo.math.*",
	//"dojo.reflect.*",
	"dojo.uri.*"
];

load("getDependencyList.js");
